package com.example.util

import android.content.Context
import android.content.SharedPreferences
import android.content.res.Configuration
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.unit.LayoutDirection
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

data class AppLanguage(
    val code: String,
    val englishName: String,
    val nativeName: String,
    val flagEmoji: String,
    val isRtl: Boolean = false
)

object LanguageManager {

    private const val PREFS_NAME = "baytulilm_app_settings_prefs"
    private const val KEY_SELECTED_LANG = "selected_language_code"
    private const val KEY_FIRST_LAUNCH = "is_first_launch_done"
    private const val KEY_SELECTED_THEME = "selected_theme_mode" // "System", "Light", "Dark"
    private const val KEY_THEME_DEFAULT_APPLIED = "is_theme_default_system_applied_v2"

    val supportedLanguages = listOf(
        AppLanguage("ur", "Urdu", "اردو", "🇵🇰", isRtl = true),
        AppLanguage("en", "English", "English", "🇺🇸", isRtl = false),
        AppLanguage("ps", "Pashto", "پښتو", "🇦🇫", isRtl = true)
    )

    private val _currentLanguage = MutableStateFlow(supportedLanguages.first())
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    private val _currentTheme = MutableStateFlow("System") // "System", "Light", "Dark"
    val currentTheme: StateFlow<String> = _currentTheme.asStateFlow()

    private val _isFirstLaunch = MutableStateFlow(true)
    val isFirstLaunch: StateFlow<Boolean> = _isFirstLaunch.asStateFlow()

    fun init(context: Context) {
        val prefs = getPrefs(context)
        val savedCode = prefs.getString(KEY_SELECTED_LANG, "ur") ?: "ur"
        val isDefaultSystemApplied = prefs.getBoolean(KEY_THEME_DEFAULT_APPLIED, false)

        val savedTheme = if (!isDefaultSystemApplied) {
            prefs.edit().putString(KEY_SELECTED_THEME, "System").putBoolean(KEY_THEME_DEFAULT_APPLIED, true).apply()
            "System"
        } else {
            prefs.getString(KEY_SELECTED_THEME, "System") ?: "System"
        }
        val firstLaunchDone = prefs.getBoolean(KEY_FIRST_LAUNCH, false)

        val englishLang = supportedLanguages.find { it.code == "en" } ?: supportedLanguages.first()
        val foundLang = supportedLanguages.find { it.code == savedCode || it.englishName.equals(savedCode, ignoreCase = true) }
            ?: englishLang

        _currentLanguage.value = foundLang
        _currentTheme.value = savedTheme
        _isFirstLaunch.value = !firstLaunchDone

        applyLocale(context, foundLang.code)
    }

    private fun getPrefs(context: Context): SharedPreferences {
        return context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    }

    fun setLanguage(context: Context, language: AppLanguage) {
        _currentLanguage.value = language
        val prefs = getPrefs(context)
        prefs.edit().putString(KEY_SELECTED_LANG, language.code).apply()
        applyLocale(context, language.code)
    }

    fun setLanguageByCodeOrName(context: Context, lang: String) {
        val englishLang = supportedLanguages.find { it.code == "en" } ?: supportedLanguages.first()
        val found = supportedLanguages.find {
            it.code.equals(lang, ignoreCase = true) || it.englishName.equals(lang, ignoreCase = true)
        } ?: englishLang
        setLanguage(context, found)
    }

    fun markFirstLaunchCompleted(context: Context) {
        _isFirstLaunch.value = false
        getPrefs(context).edit().putBoolean(KEY_FIRST_LAUNCH, true).apply()
    }

    fun setTheme(context: Context, themeMode: String) {
        _currentTheme.value = themeMode
        getPrefs(context).edit().putString(KEY_SELECTED_THEME, themeMode).apply()
    }

    private fun applyLocale(context: Context, langCode: String) {
        try {
            val locale = Locale(langCode)
            Locale.setDefault(locale)
            val resources = context.resources
            val config = Configuration(resources.configuration)
            config.setLocale(locale)
            resources.updateConfiguration(config, resources.displayMetrics)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    fun getString(key: String, langCode: String = _currentLanguage.value.code): String {
        val dict = translations[langCode]
        if (dict != null && dict.containsKey(key)) {
            return dict[key]!!
        }
        return if (langCode == "en") {
            translations["en"]?.get(key) ?: translations["ur"]?.get(key) ?: key
        } else if (langCode == "ps") {
            translations["ps"]?.get(key) ?: translations["ur"]?.get(key) ?: translations["en"]?.get(key) ?: key
        } else {
            translations["ur"]?.get(key) ?: translations["en"]?.get(key) ?: key
        }
    }
}

// Global Compose Provider for localized strings
val LocalAppLanguage = staticCompositionLocalOf { LanguageManager.supportedLanguages.first() }

@Composable
fun lStr(key: String): String {
    val currentLang = LocalAppLanguage.current
    return LanguageManager.getString(key, currentLang.code)
}

@Composable
fun LocalizedApp(
    context: Context,
    content: @Composable () -> Unit
) {
    val lang by LanguageManager.currentLanguage.collectAsState()
    val layoutDirection = if (lang.isRtl) LayoutDirection.Rtl else LayoutDirection.Ltr

    CompositionLocalProvider(
        LocalAppLanguage provides lang,
        LocalLayoutDirection provides layoutDirection
    ) {
        content()
    }
}

// Translations Map covering all keys across the application
val translations: Map<String, Map<String, String>> = mapOf(
    "ur" to mapOf(
        "app_name" to "بیت العلم اے آئی",
        "choose_language" to "اپنی زبان کا انتخاب کریں",
        "choose_language_desc" to "تمام ایپ کا مواد اور بٹن آپ کی منتخب کردہ زبان میں دکھائے جائیں گے۔",
        "search_language" to "زبان تلاش کریں...",
        "continue" to "آگے بڑھیں",
        "home" to "ہوم",
        "library" to "لائبریری",
        "darjat" to "درجات نصاب",
        "subjects" to "مضامین",
        "books" to "کتب",
        "search" to "تلاش",
        "ai_scholar" to "اے آئی عالم",
        "quiz" to "کوئز",
        "quizzes" to "کوئز و امتحان",
        "profile" to "پروفائل",
        "all" to "تمام",
        "back" to "پیچھے",
        "islamic_information" to "اسلامی معلومات",
        "asma_un_nabi" to "اسماء النبی ﷺ",
        "isma_ul_husna" to "اسماء الحسنیٰ",
        "names_of_allah" to "اسماء الحسنیٰ",
        "islamic_calendar" to "اسلامی کیلنڈر",
        "haramain_live" to "حرمین لائیو",
        "quran_pak" to "قرآن پاک",
        "tafaseer" to "قرآن کی تفاسیر",
        "quran_tafaseer" to "قرآن کی تفاسیر",
        "fatawa" to "فتاویٰ و فقہ",
        "fatawa_collections" to "مجموعہ فتاویٰ و فقہ",
        "selected_city" to "منتخب شہر",
        "change_city" to "شہر تبدیل کریں",
        "daily_hadith_badge" to "روزانہ کی حدیث مبارکہ",
        "daily_ayah_badge" to "روزانہ کی آیہ کریمہ",
        "verified_source" to "مستند ماخذ",
        "verified_quran_text" to "القرآن الکریم (تصدیق شدہ متن)",
        "next_prayer" to "اگلی نماز",
        "select_city_dialog_title" to "شہر منتخب کریں",
        "search_city_placeholder" to "شہر تلاش کریں...",
        "settings" to "سیٹنگ",
        "prayer_times" to "اوقاتِ نماز",
        "qibla" to "قبلہ نما",
        "tasbeeh" to "ڈیجیٹل تسبیح",
        "hijri_calendar" to "ہجری تقویم",
        "ramadan" to "رمضان کیلنڈر",
        "daily_quran" to "روزانہ کی آیت",
        "daily_hadith" to "روزانہ کی حدیث",
        "daily_dua" to "۱۰۰ مشہور دعائیں",
        "islamic_events" to "اسلامی ایام",
        "names_of_allah" to "اسماء الحسنیٰ",
        "nearby_mosques" to "قریبی مساجد",
        "lms" to "ایل ایم ایس لرننگ",
        "student_dashboard" to "طالب علم ڈیش بورڈ",
        "admin_panel" to "ایڈمن پینل",
        "profile" to "پروفائل",
        "settings" to "ترتیبات",
        "about" to "ہمارے بارے میں",
        "login" to "لاگ ان کریں",
        "register" to "نیا اکاؤنٹ بنائیں",
        "forgot_password" to "پاس ورڈ بھول گئے؟",
        "reset_password" to "پاس ورڈ دوبارہ ترتیب دیں",
        "reset_password_desc" to "ہم آپ کے ای میل پر پاس ورڈ ری سیٹ کرنے کی ہدایات بھیجیں گے",
        "enter_account_email" to "اکاؤنٹ ای میل درج کریں",
        "registered_email_address" to "رجسٹرڈ ای میل ایڈریس",
        "send_reset_link" to "ری سیٹ لنک بھیجیں",
        "back_to_sign_in" to "واپس سائن ان کی طرف",
        "error_invalid_email" to "براہ کرم ایک درست ای میل ایڈریس درج کریں۔",
        "error_email_not_registered" to "یہ ای میل ایڈریس رجسٹرڈ نہیں ہے۔ براہ کرم اپنا ای میل چیک کریں یا نیا اکاؤنٹ بنائیں۔",
        "success_reset_email_sent" to "پاس ورڈ کی ہدایت آپ کے ای میل پر بھیج دی گئی ہے۔",
        "error_network" to "نیٹ ورک کی خرابی۔ براہ کرم اپنا انٹرنیٹ کنیکشن چیک کریں۔",
        "firebase_not_initialized" to "فائر بیس شروع نہیں ہوا۔",
        "app_language" to "ایپ کی زبان",
        "theme_settings" to "تھیم کی ترتیبات",
        "light_theme" to "روشن سبز تھیم (Bright Green)",
        "dark_theme" to "ڈارک تھیم (Black / Dark)",
        "system_theme" to "سسٹم ڈیفالٹ",
        "downloads" to "ڈاؤن لوڈز",
        "offline" to "آف لائن",
        "offline_library" to "آف لائن لائبریری",
        "sign_out" to "سائن آؤٹ کریں",
        "save_changes" to "تبدیلیاں محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "edit_profile" to "پروفائل میں ترمیم",
        "sign_in_account" to "اپنے اکاؤنٹ میں لاگ ان کریں",
        "email_address" to "ای میل ایڈریس",
        "password" to "پاس ورڈ",
        "remember_me" to "مجھے یاد رکھیں",
        "forgot_password_q" to "پاس ورڈ بھول گئے؟",
        "continue_google" to "گوگل کے ساتھ جاری رکھیں",
        "dont_have_account_q" to "اکاؤنٹ نہیں ہے؟ ",
        "already_have_account_q" to "پہلے سے اکاؤنٹ ہے؟ ",
        "sign_up" to "سائن اپ کریں",
        "full_name" to "مکمل نام",
        "phone_number" to "فون نمبر",
        "select_role" to "کلاسیفکیشن منتخب کریں",
        "assalamu_alaikum" to "السلام علیکم",
        "search_placeholder" to "کتابیں، مضامین اور درجات تلاش کریں...",
        "ask_ai_scholar_placeholder" to "شرعی یا نصابی سوال پوچھیں...",
        "type_message" to "پیغام لکھیں...",
        "send" to "ارسال کریں",
        "email_verification_title" to "ای میل تصدیق ضروری ہے",
        "open_email_app" to "📧 ای میل ایپ کھولیں",
        "resend_verification" to "🔄 تصدیقی ای میل دوبارہ بھیجیں",
        "view_details" to "تفصیلات دیکھیں",
        "copyright_disclaimer_text" to "یہ تمام کتب صرف تعلیمی و تحقیقی مقاصد کے لیے فراہم کی گئی ہیں۔ جملہ حقوق متعلقہ مصنفین و ناشرین کے پاس محفوظ ہیں۔",
        "contact_us_copyright" to "کسی بھی کتاب یا کاپی رائٹ کی اطلاع کے لیے رابطہ کریں",
        "read_book" to "کتاب پڑھیں",
        "curriculum" to "درسِ نظامی نصاب",
        "digital_library" to "ڈیجیٹل کتب خانہ",
        "explore_library_desc" to "درسِ نظامی کے 8 درجات اور مکتبہ کتب ایکسپلور کریں",
        "search_darja_placeholder" to "درجہ یا کلاس کا نام تلاش کریں...",
        "classes_curriculum_header" to "درجات نصاب (8 درجات)",
        "active" to "فعال",
        "open_class" to "کلاس کھولیں",
        "curriculum_progress" to "نصابی پیش رفت",
        "digital_madrasa" to "ڈیجیٹل مدرسہ",
        "live_classes" to "لائیو کلاسز",
        "video_courses" to "ویڈیو کورسز",
        "audio_daroos" to "آڈیو دروس",
        "qa_forum" to "سوال و جواب فورم",
        "messages_chat" to "پیغامات و چیٹ",
        "ocr_assistant" to "کتاب پیج او سی آر",
        "parent_panel" to "سرپرست / والد پینل",
        "my_library" to "میرا کتب خانہ",
        "bookmarks" to "نشان زدہ (بک مارکس)",
        "favorites" to "پسندیدہ کتابیں",
        "recent_reading" to "حالیہ مطالعہ",
        "downloads_manager" to "ڈاؤن لوڈز مینیجر",
        "welcome_back" to "خوش آمدید",
        "daily_verse" to "آج کی قرآنی آیت",
        "quick_actions" to "فوری رسائی",
        "tools_hub" to "اسلامی ٹولز",
        "dars_e_nizami_classes" to "درسِ نظامی درجات (نصاب)",
        "view_all" to "سب دیکھیں",
        "ai_scholarly_assistant" to "اے آئی علمی معاون",
        "ask_anything_islamic" to "فقہ، حدیث یا نصاب کا کوئی بھی سوال پوچھیں",
        "featured_books" to "منتخب و مشہور کتب",
        "recent_activity" to "حالیہ سرگرمی",
        "no_recent_activity" to "کوئی حالیہ سرگرمی نہیں ہے",
        "author" to "مصنف",
        "download_pdf" to "پی ڈی ایف ڈاؤن لوڈ کریں",
        "downloading" to "ڈاؤن لوڈ ہو رہا ہے...",
        "downloaded" to "ڈاؤن لوڈ مکمل",
        "downloaded_100" to "ڈاؤن لوڈ مکمل 100%",
        "cancel_download" to "ڈاؤن لوڈ منسوخ کریں",
        "download_cancelled" to "ڈاؤن لوڈ منسوخ کر دیا گیا",
        "read_now" to "ابھی پڑھیں",
        "ask_ai_about_book" to "اس کتاب کے بارے میں AI سے پوچھیں",
        "summary" to "خلاصہ کلام",
        "bookmarks_and_notes" to "بک مارکس اور نوٹس",
        "add_bookmark" to "بک مارک شامل کریں",
        "remove_bookmark" to "بک مارک ہٹائیں",
        "add_note" to "نوٹ لکھیں",
        "search_in_book" to "کتاب میں تلاش کریں...",
        "font_size" to "فونٹ سائز",
        "night_mode" to "نائٹ موڈ",
        "search_hint" to "کتاب کا نام، مصنف، یا موضوع درج کریں...",
        "no_results" to "کوئی نتائج نہیں ملے",
        "my_bookmarks" to "میرے نشان زدہ صفحات",
        "no_bookmarks" to "کوئی بک مارک نہیں ہے",
        "my_favorites" to "میری پسندیدہ کتب",
        "no_favorites" to "کوئی پسندیدہ کتاب شامل نہیں کی گئی",
        "recent_history" to "حالیہ پڑھائی کی تاریخ",
        "clear_history" to "تاریخ صاف کریں",
        "downloaded_books" to "ڈاؤن لوڈ شدہ کتابیں (آف لائن)",
        "no_downloads" to "کوئی ڈاؤن لوڈ کی گئی کتاب نہیں ہے",
        "delete" to "حذف کریں",
        "start_quiz" to "کوئز شروع کریں",
        "question_progress" to "سوال",
        "submit" to "جمع کرائیں",
        "next_question" to "اگلا سوال",
        "score" to "آپ کا اسکور",
        "quiz_completed" to "کوئز مکمل ہو گیا!",
        "try_again" to "دوبارہ کوشش کریں",
        "type_question" to "اپنا سوال یہاں تحریر کریں...",
        "quick_prompts" to "تجویز کردہ سوالات",
        "clear_chat" to "چیٹ صاف کریں",
        "copy_response" to "جواب کاپی کریں",
        "ai_thinking" to "اے آئی جواب سوچ رہا ہے...",
        "main_navigation" to "بنیادی نیویگیشن",
        "ai_teacher" to "اے آئی استاد سسٹم"
    ),
    "en" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Choose Your Language",
        "islamic_information" to "Islamic Information",
        "asma_un_nabi" to "Names of the Prophet ﷺ",
        "isma_ul_husna" to "99 Names of Allah",
        "names_of_allah" to "99 Names of Allah",
        "haramain_live" to "Haramain Live",
        "islamic_calendar" to "Islamic Calendar",
        "quran_pak" to "Holy Quran",
        "tafaseer" to "Quran Tafseer",
        "quran_tafaseer" to "Quran Tafseer",
        "fatawa" to "Fatawa & Fiqh",
        "fatawa_collections" to "Fatawa & Fiqh Collections",
        "selected_city" to "Selected City",
        "change_city" to "Change City",
        "daily_hadith_badge" to "Daily Blessed Hadith",
        "daily_ayah_badge" to "Daily Quran Verse",
        "verified_source" to "Verified Source",
        "verified_quran_text" to "The Holy Quran (Verified Text)",
        "next_prayer" to "Next Prayer",
        "select_city_dialog_title" to "Select City",
        "search_city_placeholder" to "Search city...",
        "choose_language_desc" to "Select your preferred language for the entire app experience.",
        "search_language" to "Search language...",
        "continue" to "Continue",
        "home" to "Home",
        "library" to "Library",
        "darjat" to "Darjat Curriculum",
        "subjects" to "Subjects",
        "books" to "Books",
        "search" to "Search",
        "ai_scholar" to "AI Scholar",
        "quiz" to "Quiz",
        "prayer_times" to "Prayer Times",
        "qibla" to "Qibla Direction",
        "tasbeeh" to "Digital Tasbeeh",
        "hijri_calendar" to "Hijri Calendar",
        "ramadan" to "Ramadan Calendar",
        "daily_quran" to "Daily Quran",
        "daily_hadith" to "Daily Hadith",
        "daily_dua" to "Daily Duas",
        "islamic_events" to "Islamic Events",
        "names_of_allah" to "99 Names of Allah",
        "nearby_mosques" to "Nearby Mosques",
        "lms" to "LMS Learning",
        "student_dashboard" to "Student Dashboard",
        "admin_panel" to "Admin Panel",
        "profile" to "Profile",
        "settings" to "Settings",
        "about" to "About & Contact",
        "login" to "Sign In",
        "register" to "Create Account",
        "forgot_password" to "Reset Password",
        "reset_password" to "Reset Password",
        "reset_password_desc" to "We will send instructions to your email",
        "enter_account_email" to "Enter Account Email",
        "registered_email_address" to "Registered Email Address",
        "send_reset_link" to "Send Reset Link",
        "back_to_sign_in" to "Back to Sign In",
        "error_invalid_email" to "Please enter a valid email address.",
        "error_email_not_registered" to "This email address is not registered. Please check your email or create a new account.",
        "success_reset_email_sent" to "Password reset instructions have been sent to your email.",
        "error_network" to "Network error. Please check your internet connection.",
        "firebase_not_initialized" to "Firebase Auth is not initialized.",
        "app_language" to "App Language",
        "theme_settings" to "Theme Settings",
        "light_theme" to "Bright Green Theme",
        "dark_theme" to "Dark Theme (Black / Dark)",
        "system_theme" to "System Default",
        "downloads" to "Downloads",
        "offline" to "Offline Library",
        "sign_out" to "Sign Out Account",
        "save_changes" to "Save Changes",
        "cancel" to "Cancel",
        "edit_profile" to "Edit Profile Details",
        "sign_in_account" to "Sign In to Your Account",
        "email_address" to "Email Address",
        "password" to "Password",
        "remember_me" to "Remember Me",
        "forgot_password_q" to "Forgot Password?",
        "continue_google" to "Continue with Google",
        "dont_have_account_q" to "Don't have an account? ",
        "already_have_account_q" to "Already have an account? ",
        "sign_up" to "Sign Up",
        "full_name" to "Full Name",
        "phone_number" to "Phone Number",
        "select_role" to "Select Account Role",
        "assalamu_alaikum" to "Assalamu Alaikum",
        "search_placeholder" to "Search Books, Subjects, Darjat or Authors...",
        "ask_ai_scholar_placeholder" to "Ask any Islamic or Dars-e-Nizami question...",
        "type_message" to "Type your message...",
        "send" to "Send",
        "email_verification_title" to "Email Verification Required",
        "open_email_app" to "📧 Open Email App",
        "resend_verification" to "🔄 Resend Verification Email",
        "view_details" to "View Details",
        "read_book" to "Read Book",
        "curriculum" to "Dars-e-Nizami Curriculum",
        "digital_library" to "Digital Library",
        "explore_library_desc" to "Explore Dars-e-Nizami Academic Years & Kutub Library",
        "search_darja_placeholder" to "Search Darja (Class) name...",
        "classes_curriculum_header" to "Classes / Darjat Curriculum (8 Darjat)",
        "active" to "Active",
        "open_class" to "Open Class",
        "curriculum_progress" to "Curriculum Progress",
        "digital_madrasa" to "Digital Madrasa",
        "live_classes" to "Live Classes",
        "video_courses" to "Video Courses",
        "audio_daroos" to "Audio Daroos",
        "qa_forum" to "Q&A Forum",
        "messages_chat" to "Messages & Chat",
        "ocr_assistant" to "Book Page OCR",
        "parent_panel" to "Parent Panel",
        "my_library" to "My Library",
        "bookmarks" to "Bookmarks",
        "favorites" to "Favorites",
        "recent_reading" to "Recent Reading",
        "downloads_manager" to "Downloads Manager",
        "welcome_back" to "Welcome Back",
        "daily_verse" to "Daily Quran Verse",
        "quick_actions" to "Quick Actions",
        "tools_hub" to "Tools Hub",
        "dars_e_nizami_classes" to "Dars-e-Nizami Classes",
        "view_all" to "View All",
        "ai_scholarly_assistant" to "AI Scholarly Assistant",
        "ask_anything_islamic" to "Ask any Islamic or curriculum question",
        "featured_books" to "Featured Books",
        "recent_activity" to "Recent Activity",
        "no_recent_activity" to "No recent activity",
        "author" to "Author",
        "download_pdf" to "Download PDF",
        "downloading" to "Downloading...",
        "downloaded" to "Downloaded",
        "downloaded_100" to "Downloaded 100%",
        "cancel_download" to "Cancel Download",
        "download_cancelled" to "Download cancelled",
        "read_now" to "Read Now",
        "ask_ai_about_book" to "Ask AI about this Book",
        "summary" to "Summary & Overview",
        "bookmarks_and_notes" to "Bookmarks & Notes",
        "add_bookmark" to "Add Bookmark",
        "remove_bookmark" to "Remove Bookmark",
        "add_note" to "Add Note",
        "search_in_book" to "Search in book...",
        "font_size" to "Font Size",
        "night_mode" to "Night Mode",
        "search_hint" to "Enter book title, author, or topic...",
        "no_results" to "No results found",
        "my_bookmarks" to "My Bookmarks",
        "no_bookmarks" to "No bookmarks added yet",
        "my_favorites" to "My Favorite Books",
        "no_favorites" to "No favorite books added yet",
        "recent_history" to "Recent Reading History",
        "clear_history" to "Clear History",
        "downloaded_books" to "Downloaded Books (Offline)",
        "no_downloads" to "No downloaded books yet",
        "delete" to "Delete",
        "start_quiz" to "Start Quiz",
        "question_progress" to "Question",
        "submit" to "Submit",
        "next_question" to "Next Question",
        "score" to "Your Score",
        "quiz_completed" to "Quiz Completed!",
        "try_again" to "Try Again",
        "type_question" to "Type your question here...",
        "quick_prompts" to "Suggested Questions",
        "clear_chat" to "Clear Chat",
        "copy_response" to "Copy Answer",
        "ai_thinking" to "AI Scholar is thinking...",
        "main_navigation" to "Main Navigation",
        "ai_teacher" to "AI Teacher System"
    ),
    "tr" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Dilinizi Seçin",
        "islamic_information" to "İslami Bilgiler",
        "choose_language_desc" to "Tüm uygulama deneyimi için tercih ettiğiniz dili seçin.",
        "search_language" to "Dil ara...",
        "continue" to "Devam Et",
        "home" to "Ana Sayfa",
        "library" to "Kütüphane",
        "darjat" to "Müfredat",
        "subjects" to "Dersler",
        "books" to "Kitaplar",
        "search" to "Ara",
        "ai_scholar" to "Yapay Zeka Alim",
        "quiz" to "Testler",
        "prayer_times" to "Namaz Vakitleri",
        "qibla" to "Kıble Yönü",
        "tasbeeh" to "Dijital Tesbih",
        "hijri_calendar" to "Hicri Takvim",
        "ramadan" to "Ramazan Takvimi",
        "daily_quran" to "Günün Ayeti",
        "daily_hadith" to "Günün Hadisi",
        "daily_dua" to "Günün Duası",
        "islamic_events" to "Dini Günler",
        "names_of_allah" to "Esmaül Hüsna",
        "nearby_mosques" to "Yakındaki Camiler",
        "lms" to "LMS Öğrenim",
        "student_dashboard" to "Öğrenci Paneli",
        "admin_panel" to "Yönetici Paneli",
        "profile" to "Profil",
        "settings" to "Ayarlar",
        "about" to "Hakkında",
        "login" to "Giriş Yap",
        "register" to "Kayıt Ol",
        "forgot_password" to "Şifremi Unuttum",
        "app_language" to "Uygulama Dili",
        "theme_settings" to "Tema Ayarları",
        "light_theme" to "Açık Tema",
        "dark_theme" to "Koyu Tema",
        "system_theme" to "Sistem Varsayılanı",
        "downloads" to "İndirilenler",
        "offline" to "Çevrimdışı Kütüphane",
        "sign_out" to "Çıkış Yap",
        "save_changes" to "Değişiklikleri Kaydet",
        "cancel" to "İptal",
        "edit_profile" to "Profili Düzenle"
    ),
    "id" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Pilih Bahasa Anda",
        "islamic_information" to "Informasi Islam",
        "choose_language_desc" to "Pilih bahasa pilihan Anda untuk seluruh pengalaman aplikasi.",
        "search_language" to "Cari bahasa...",
        "continue" to "Lanjutkan",
        "home" to "Beranda",
        "library" to "Perpustakaan",
        "darjat" to "Kurikulum",
        "subjects" to "Mata Pelajaran",
        "books" to "Buku",
        "search" to "Cari",
        "ai_scholar" to "Cendekiawan AI",
        "quiz" to "Kuis",
        "prayer_times" to "Jadwal Sholat",
        "qibla" to "Arah Kiblat",
        "tasbeeh" to "Tasbih Digital",
        "hijri_calendar" to "Kalender Hijriah",
        "ramadan" to "Jadwal Ramadan",
        "daily_quran" to "Ayat Harian",
        "daily_hadith" to "Hadis Harian",
        "daily_dua" to "Doa Harian",
        "islamic_events" to "Hari Besar Islam",
        "names_of_allah" to "Asmaul Husna",
        "nearby_mosques" to "Masjid Terdekat",
        "lms" to "Pembelajaran LMS",
        "student_dashboard" to "Dasbor Siswa",
        "admin_panel" to "Panel Admin",
        "profile" to "Profil",
        "settings" to "Pengaturan",
        "about" to "Tentang",
        "login" to "Masuk",
        "register" to "Daftar",
        "forgot_password" to "Lupa Kata Sandi",
        "app_language" to "Bahasa Aplikasi",
        "theme_settings" to "Pengaturan Tema",
        "light_theme" to "Tema Terang",
        "dark_theme" to "Tema Gelap",
        "system_theme" to "Default Sistem",
        "downloads" to "Unduhan",
        "offline" to "Perpustakaan Offline",
        "sign_out" to "Keluar",
        "save_changes" to "Simpan Perubahan",
        "cancel" to "Batal",
        "edit_profile" to "Edit Profil"
    ),
    "hi" to mapOf(
        "app_name" to "बैतुल इल्म एआई",
        "choose_language" to "अपनी भाषा चुनें",
        "islamic_information" to "इस्लामी जानकारी",
        "choose_language_desc" to "संपूर्ण ऐप अनुभव के लिए अपनी पसंदीदा भाषा का चयन करें।",
        "search_language" to "भाषा खोजें...",
        "continue" to "आगे बढ़ें",
        "home" to "होम",
        "library" to "पुस्तकालय",
        "darjat" to "पाठ्यक्रम",
        "subjects" to "विषय",
        "books" to "पुस्तकें",
        "search" to "खोजें",
        "ai_scholar" to "एआई विद्वान",
        "quiz" to "क्विज़",
        "prayer_times" to "नमाज़ का समय",
        "qibla" to "क़िबला दिशा",
        "tasbeeh" to "डिजिटल तस्बीह",
        "hijri_calendar" to "हिजरी कैलेंडर",
        "ramadan" to "रमज़ान कैलेंडर",
        "daily_quran" to "दैनिक आयत",
        "daily_hadith" to "दैनिक हदीस",
        "daily_dua" to "दैनिक दुआ",
        "islamic_events" to "इस्लामिक कार्यक्रम",
        "names_of_allah" to "अल्लाह के 99 नाम",
        "nearby_mosques" to "पास की मस्जिदें",
        "lms" to "एलएमएस सीखना",
        "student_dashboard" to "छात्र डैशबोर्ड",
        "admin_panel" to "एडमिन पैनल",
        "profile" to "प्रोफ़ाइल",
        "settings" to "सेटिंग्स",
        "about" to "के बारे में",
        "login" to "साइन इन करें",
        "register" to "खाता बनाएं",
        "forgot_password" to "पासवर्ड भूल गए?",
        "app_language" to "ऐप की भाषा",
        "theme_settings" to "थीम सेटिंग्स",
        "light_theme" to "लाइट थीम",
        "dark_theme" to "डार्क थीम",
        "system_theme" to "सिस्टम डिफ़ॉल्ट",
        "downloads" to "डाउनलोड",
        "offline" to "ऑफ़लाइन लाइब्रेरी",
        "sign_out" to "साइन आउट",
        "save_changes" to "बदलाव सहेजें",
        "cancel" to "रद्द करें",
        "edit_profile" to "प्रोफ़ाइल संपादित करें"
    ),
    "fr" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Choisissez votre langue",
        "islamic_information" to "Informations Islamiques",
        "choose_language_desc" to "Sélectionnez votre langue préférée pour l'ensemble de l'application.",
        "search_language" to "Rechercher une langue...",
        "continue" to "Continuer",
        "home" to "Accueil",
        "library" to "Bibliothèque",
        "darjat" to "Programme",
        "subjects" to "Matières",
        "books" to "Livres",
        "search" to "Rechercher",
        "ai_scholar" to "Savant IA",
        "quiz" to "Quiz",
        "prayer_times" to "Heures de prière",
        "qibla" to "Direction Qibla",
        "tasbeeh" to "Chapelet digital",
        "hijri_calendar" to "Calendrier Hégirien",
        "ramadan" to "Calendrier Ramadan",
        "daily_quran" to "Verset du jour",
        "daily_hadith" to "Hadith du jour",
        "daily_dua" to "Invocations du jour",
        "islamic_events" to "Événements islamiques",
        "names_of_allah" to "99 Noms d'Allah",
        "nearby_mosques" to "Mosquées à proximité",
        "lms" to "Apprentissage LMS",
        "student_dashboard" to "Tableau de bord étudiant",
        "admin_panel" to "Panneau Admin",
        "profile" to "Profil",
        "settings" to "Paramètres",
        "about" to "À propos",
        "login" to "Connexion",
        "register" to "Créer un compte",
        "forgot_password" to "Mot de passe oublié",
        "app_language" to "Langue de l'application",
        "theme_settings" to "Thème",
        "light_theme" to "Thème clair",
        "dark_theme" to "Thème sombre",
        "system_theme" to "Par défaut",
        "downloads" to "Téléchargements",
        "offline" to "Bibliothèque hors ligne",
        "sign_out" to "Se déconnecter",
        "save_changes" to "Enregistrer",
        "cancel" to "Annuler",
        "edit_profile" to "Modifier le profil"
    ),
    "de" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Wählen Sie Ihre Sprache",
        "islamic_information" to "Islamische Informationen",
        "choose_language_desc" to "Wählen Sie Ihre bevorzugte Sprache für die gesamte App.",
        "search_language" to "Sprache suchen...",
        "continue" to "Weiter",
        "home" to "Startseite",
        "library" to "Bibliothek",
        "darjat" to "Lehrplan",
        "subjects" to "Fächer",
        "books" to "Bücher",
        "search" to "Suchen",
        "ai_scholar" to "KI Gelehrter",
        "quiz" to "Quiz",
        "prayer_times" to "Gebetszeiten",
        "qibla" to "Qibla-Richtung",
        "tasbeeh" to "Digitaler Tasbih",
        "hijri_calendar" to "Hijri-Kalender",
        "ramadan" to "Ramadan-Kalender",
        "daily_quran" to "Tägliche Koranseite",
        "daily_hadith" to "Täglicher Hadith",
        "daily_dua" to "Tägliche Bittgebete",
        "islamic_events" to "Islamische Ereignisse",
        "names_of_allah" to "99 Namen Allahs",
        "nearby_mosques" to "Moscheen in der Nähe",
        "lms" to "LMS Lernen",
        "student_dashboard" to "Studenten-Dashboard",
        "admin_panel" to "Admin-Bereich",
        "profile" to "Profil",
        "settings" to "Einstellungen",
        "about" to "Über uns",
        "login" to "Anmelden",
        "register" to "Konto erstellen",
        "forgot_password" to "Passwort vergessen",
        "app_language" to "App-Sprache",
        "theme_settings" to "Design-Einstellungen",
        "light_theme" to "Helles Design",
        "dark_theme" to "Dunkles Design",
        "system_theme" to "Systemstandard",
        "downloads" to "Downloads",
        "offline" to "Offline-Bibliothek",
        "sign_out" to "Abmelden",
        "save_changes" to "Änderungen speichern",
        "cancel" to "Abbrechen",
        "edit_profile" to "Profil bearbeiten"
    ),
    "es" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "Elija su idioma",
        "islamic_information" to "Información Islámica",
        "choose_language_desc" to "Seleccione su idioma preferido para toda la experiencia de la aplicación.",
        "search_language" to "Buscar idioma...",
        "continue" to "Continuar",
        "home" to "Inicio",
        "library" to "Biblioteca",
        "darjat" to "Currículo",
        "subjects" to "Materias",
        "books" to "Libros",
        "search" to "Buscar",
        "ai_scholar" to "Erudito IA",
        "quiz" to "Cuestionarios",
        "prayer_times" to "Horarios de oración",
        "qibla" to "Dirección Qibla",
        "tasbeeh" to "Tasbih digital",
        "hijri_calendar" to "Calendario Hégira",
        "ramadan" to "Calendario de Ramadan",
        "daily_quran" to "Versículo diario",
        "daily_hadith" to "Hadiz diario",
        "daily_dua" to "Súplicas diarias",
        "islamic_events" to "Eventos islámicos",
        "names_of_allah" to "99 Nombres de Allah",
        "nearby_mosques" to "Mezquitas cercanas",
        "lms" to "Aprendizaje LMS",
        "student_dashboard" to "Panel de Estudiante",
        "admin_panel" to "Panel de Admin",
        "profile" to "Perfil",
        "settings" to "Ajustes",
        "about" to "Acerca de",
        "login" to "Iniciar Sesión",
        "register" to "Crear Cuenta",
        "forgot_password" to "Olvidé mi contraseña",
        "app_language" to "Idioma de la aplicación",
        "theme_settings" to "Ajustes de Tema",
        "light_theme" to "Tema Claro",
        "dark_theme" to "Tema Oscuro",
        "system_theme" to "Predeterminado del Sistema",
        "downloads" to "Descargas",
        "offline" to "Biblioteca Fuera de Línea",
        "sign_out" to "Cerrar Sesión",
        "save_changes" to "Guardar Cambios",
        "cancel" to "Cancelar",
        "edit_profile" to "Editar Perfil"
    ),
    "ru" to mapOf(
        "app_name" to "Байтул Ильм ИИ",
        "choose_language" to "Выберите язык",
        "islamic_information" to "Исламская информация",
        "choose_language_desc" to "Выберите предпочитаемый язык для всей работы с приложением.",
        "search_language" to "Поиск языка...",
        "continue" to "Продолжить",
        "home" to "Главная",
        "library" to "Библиотека",
        "darjat" to "Программа",
        "subjects" to "Предметы",
        "books" to "Книги",
        "search" to "Поиск",
        "ai_scholar" to "ИИ Ученый",
        "quiz" to "Викторина",
        "prayer_times" to "Время намаза",
        "qibla" to "Направление Киблы",
        "tasbeeh" to "Цифровой тасбих",
        "hijri_calendar" to "Календарь Хиджры",
        "ramadan" to "Календарь Рамадана",
        "daily_quran" to "Аят дня",
        "daily_hadith" to "Хадис дня",
        "daily_dua" to "Дуа дня",
        "islamic_events" to "Исламские события",
        "names_of_allah" to "99 Имен Аллаха",
        "nearby_mosques" to "Ближайшие мечети",
        "lms" to "LMS Обучение",
        "student_dashboard" to "Панель студента",
        "admin_panel" to "Панель администратора",
        "profile" to "Профиль",
        "settings" to "Настройки",
        "about" to "О приложении",
        "login" to "Войти",
        "register" to "Регистрация",
        "forgot_password" to "Забыли пароль?",
        "app_language" to "Язык приложения",
        "theme_settings" to "Тема оформления",
        "light_theme" to "Светлая тема",
        "dark_theme" to "Тёмная тема",
        "system_theme" to "Системная",
        "downloads" to "Загрузки",
        "offline" to "Офлайн библиотека",
        "sign_out" to "Выйти",
        "save_changes" to "Сохранить изменения",
        "cancel" to "Отмена",
        "edit_profile" to "Редактировать профиль"
    ),
    "zh" to mapOf(
        "app_name" to "Baytul Ilm AI",
        "choose_language" to "选择您的语言",
        "islamic_information" to "伊斯兰信息",
        "choose_language_desc" to "选择您偏好的语言以应用到整个应用体验。",
        "search_language" to "搜索语言...",
        "continue" to "继续",
        "home" to "首页",
        "library" to "图书馆",
        "darjat" to "课程大纲",
        "subjects" to "科目",
        "books" to "图书",
        "search" to "搜索",
        "ai_scholar" to "AI 学者",
        "quiz" to "测验",
        "prayer_times" to "礼拜时间",
        "qibla" to "朝向指南针",
        "tasbeeh" to "电子赞珠",
        "hijri_calendar" to "伊斯兰历",
        "ramadan" to "斋月日历",
        "daily_quran" to "每日古兰经",
        "daily_hadith" to "每日圣训",
        "daily_dua" to "每日祈祷",
        "islamic_events" to "伊斯兰节日",
        "names_of_allah" to "真主99个尊名",
        "nearby_mosques" to "附近清真寺",
        "lms" to "LMS 学习系统",
        "student_dashboard" to "学生仪表板",
        "admin_panel" to "管理面板",
        "profile" to "个人资料",
        "settings" to "设置",
        "about" to "关于",
        "login" to "登录",
        "register" to "注册账号",
        "forgot_password" to "重置密码",
        "app_language" to "应用语言",
        "theme_settings" to "主题设置",
        "light_theme" to "浅色模式",
        "dark_theme" to "深色模式",
        "system_theme" to "跟随系统",
        "downloads" to "下载管理",
        "offline" to "离线图书",
        "sign_out" to "退出登录",
        "save_changes" to "保存修改",
        "cancel" to "取消",
        "edit_profile" to "编辑个人资料"
    ),
    "ps" to mapOf(
        "app_name" to "بیت العلم آی ای",
        "choose_language" to "خپله ژبه وټاکئ",
        "islamic_information" to "اسلامي معلومات",
        "asma_un_nabi" to "د نبي کریم ﷺ نومونه",
        "isma_ul_husna" to "د الله ۹۹ مبارک نومونه",
        "names_of_allah" to "د الله ۹۹ مبارک نومونه",
        "haramain_live" to "حرمین شریفین ژوندی",
        "islamic_calendar" to "اسلامي تقویم",
        "quran_pak" to "قرآن کریم",
        "tafaseer" to "د قرآن تفاسیر",
        "quran_tafaseer" to "د قرآن تفاسیر",
        "fatawa" to "فتاویٰ او فقه",
        "fatawa_collections" to "د فتاویٰ او فقه ټولګه",
        "selected_city" to "ټاکل شوی ښار",
        "change_city" to "ښار بدل کړئ",
        "daily_hadith_badge" to "د نن ورځې مبارک حدیث",
        "daily_ayah_badge" to "د نن ورځې مبارکه آیت",
        "verified_source" to "معتبره سرچینه",
        "verified_quran_text" to "قرآن کریم (تصدیق شوی متن)",
        "next_prayer" to "راتلونکی لمونځ",
        "select_city_dialog_title" to "ښار وټاکئ",
        "search_city_placeholder" to "ښار وپلټئ...",
        "choose_language_desc" to "د ټولو برنامو او درسي تجربو لپاره خپله خوښه ژبه وټاکئ.",
        "search_language" to "ژبه وپلټئ...",
        "continue" to "مخکې ولاړ شئ",
        "home" to "کورپاڼه",
        "library" to "کتابتون",
        "darjat" to "درجات او نصاب",
        "subjects" to "مضمونونه",
        "books" to "کتابونه",
        "search" to "پلټنه",
        "ai_scholar" to "ای ای عالم",
        "quiz" to "ازموینه او کوئز",
        "quizzes" to "ازموینه او کوئز",
        "all" to "ټول",
        "back" to "شاته",
        "prayer_times" to "د لمونځ وختونه",
        "qibla" to "د قبلې لوری",
        "tasbeeh" to "ډیجیټل تسبیح",
        "hijri_calendar" to "هجري کلیز",
        "ramadan" to "د روژې کلیز",
        "daily_quran" to "د نن ورځې قرآني آیت",
        "daily_hadith" to "د نن ورځ حدیث شریف",
        "daily_dua" to "۱۰۰ مشهورې دعاوې",
        "islamic_events" to "اسلامي مهمې ورځې",
        "names_of_allah" to "د الله تعالی ۹۹ نومونه",
        "nearby_mosques" to "نېږدې جوماتونه",
        "lms" to "ایل ایم ایس زده کړه",
        "student_dashboard" to "د زده کوونکي ډشبورډ",
        "admin_panel" to "اډمین پینل",
        "profile" to "پروفایل",
        "settings" to "ترتیبات",
        "about" to "زموږ په اړه او اړیکه",
        "login" to "ننوځئ (لاګ ان)",
        "register" to "نوی اکاونټ جوړ کړئ",
        "forgot_password" to "پاسورډ مو هېر شوی؟",
        "reset_password" to "د پاسورډ بیا تنظیمول",
        "reset_password_desc" to "موږ به ستاسو بریښنالیک ته لارښوونې واستوو",
        "enter_account_email" to "د حساب بریښنالیک دننه کړئ",
        "registered_email_address" to "راجستر شوی بریښنالیک پته",
        "send_reset_link" to "د بیا تنظیم کولو لینک واستوئ",
        "back_to_sign_in" to "بیرته ننوتلو ته",
        "error_invalid_email" to "مهرباني وکړئ یو باوري بریښنالیک پته دننه کړئ.",
        "error_email_not_registered" to "دا بریښنالیک پته راجستر شوې نه ده. مهرباني وکړئ خپل بریښنالیک وګورئ یا نوی حساب جوړ کړئ.",
        "success_reset_email_sent" to "ستاسو بریښنالیک ته د پټنوم بیا تنظیمولو لارښوونې لیږل شوي.",
        "error_network" to "د شبکې تیروتنه. مهرباني وکړئ خپل انټرنیټ اړیکه وګورئ.",
        "firebase_not_initialized" to "فائر بیس نه دی پیل شوی.",
        "app_language" to "د اپلیکیشن ژبه",
        "theme_settings" to "د بڼې تنظیمات",
        "light_theme" to "روښانه بڼه",
        "dark_theme" to "تیره بڼه",
        "system_theme" to "د سیسټم مطابق",
        "downloads" to "ډاونلوډونه",
        "offline" to "افلاین کتابتون",
        "sign_out" to "وتل (سائن آؤټ)",
        "save_changes" to "بدلونونه خوندي کړئ",
        "cancel" to "لغوه کول",
        "edit_profile" to "پروفایل ایډیټ کړئ",
        "sign_in_account" to "خپل اکاونټ ته ننوځئ",
        "email_address" to "ایمیلی ادرس",
        "password" to "پاسورډ",
        "remember_me" to "ما یاد وساتئ",
        "forgot_password_q" to "پاسورډ مو هېر شوی؟",
        "continue_google" to "د ګوګل سره دوام ورکړئ",
        "dont_have_account_q" to "اکاونټ نه لرئ؟ ",
        "already_have_account_q" to "مخکې له مخکې اکاونټ لرئ؟ ",
        "sign_up" to "سائن اپ کړئ",
        "full_name" to "پشپړ نوم",
        "phone_number" to "د تلیفون شمیره",
        "select_role" to "خپله دنده وټاکئ",
        "assalamu_alaikum" to "السلام علیکم",
        "search_placeholder" to "کتابونه، مضمونونه او درجات وپلټئ...",
        "ask_ai_scholar_placeholder" to "شرعي یا نصابي پوښتنه وپوښتئ...",
        "type_message" to "خپل پیغام ولیکئ...",
        "send" to "لیږل",
        "email_verification_title" to "د ایمیل تصدیق اړین دی",
        "open_email_app" to "📧 د ایمیل اپلیکیشن خلاص کړئ",
        "resend_verification" to "🔄 تصدیقي ایمیل بیا ولېږئ",
        "view_details" to "تفصیلات وګورئ",
        "read_book" to "کتاب لولئ",
        "curriculum" to "د درسِ نظامی نصاب",
        "digital_library" to "ډیجیټل کتابتون",
        "explore_library_desc" to "د درسِ نظامی ۸ درجات او کتابونه وپلټئ",
        "search_darja_placeholder" to "د درجې یا ټولګي نوم وپلټئ...",
        "classes_curriculum_header" to "درجات او نصاب (۸ ټولګي)",
        "active" to "فعال",
        "open_class" to "ټولګی خلاص کړئ",
        "curriculum_progress" to "نصابي پرمختګ",
        "digital_madrasa" to "ډیجیټل مدرسه",
        "live_classes" to "آنلاین لایو ټولګي",
        "video_courses" to "ویډیویي کورسونه",
        "audio_daroos" to "صوتی درسونه",
        "qa_forum" to "پوښتنې او ځوابونه",
        "messages_chat" to "پیغامونه او چیټ",
        "ocr_assistant" to "د کتاب پاڼې سکین (OCR)",
        "parent_panel" to "د سرپرست / پلار پینل",
        "my_library" to "زما کتابتون",
        "bookmarks" to "نښه شوي (بک مارکونه)",
        "favorites" to "خوښ شوي کتابونه",
        "recent_reading" to "وروستی لوستل شوی",
        "downloads_manager" to "د ډانلوډونو تنظیمونکی",
        "welcome_back" to "ښه راغلاست",
        "daily_verse" to "د نن ورځی قرآني آیت",
        "quick_actions" to "چټک لاسرسی",
        "tools_hub" to "اسلامي اوزار",
        "dars_e_nizami_classes" to "د درسِ نظامي درجات (نصاب)",
        "view_all" to "ټول وګورئ",
        "ai_scholarly_assistant" to "ای ای علمي مرستیال",
        "ask_anything_islamic" to "د فقهې، حدیث یا نصاب هره پوښتنه وپوښتئ",
        "featured_books" to "مشهور او غوره کتابونه",
        "recent_activity" to "وروستي فعالیتونه",
        "no_recent_activity" to "هیڅ وروستی فعالیت نشته",
        "author" to "لیکوال",
        "download_pdf" to "پی ډی ایف ډاونلوډ کړئ",
        "downloading" to "ډاونلوډ کیږي...",
        "downloaded" to "ډاونلوډ بشپړ شو",
        "read_now" to "اوس یې ولولئ",
        "ask_ai_about_book" to "د دې کتاب په اړه له AI وپوښتئ",
        "summary" to "خلاصه",
        "bookmarks_and_notes" to "بک مارکونه او یادښتونه",
        "add_bookmark" to "بک مارک اضافه کړئ",
        "remove_bookmark" to "بک مارک لېرې کړئ",
        "add_note" to "یادښت ولیکئ",
        "search_in_book" to "په کتاب کې پلټنه وکړئ...",
        "font_size" to "د ليکنې اندازه",
        "night_mode" to "د شپې حالت",
        "search_hint" to "د کتاب نوم، لیکوال، یا موضوع داخل کړئ...",
        "no_results" to "هیڅ پایله ونه موندل شوه",
        "my_bookmarks" to "زما نښه شوې پاڼې",
        "no_bookmarks" to "هیڅ بک مارک نشته",
        "my_favorites" to "زما خوښ شوي کتابونه",
        "no_favorites" to "هیڅ خوښ شوی کتاب نشته",
        "recent_history" to "د لوستلو وروستۍ تاریخچه",
        "clear_history" to "تاریخچه پاکه کړئ",
        "downloaded_books" to "ډاونلوډ شوي کتابونه (افلاین)",
        "no_downloads" to "هیڅ ډاونلوډ شوی کتاب نشته",
        "delete" to "حذف کړئ",
        "start_quiz" to "ازموینه پیل کړئ",
        "question_progress" to "پوښتنه",
        "submit" to "وسپارئ",
        "next_question" to "بله پوښتنه",
        "score" to "ستاسو نمره",
        "quiz_completed" to "ازموینه بشپړه شوه!",
        "try_again" to "دوباره کوشش وکړئ",
        "type_question" to "خپله پوښتنه دلته ولیکئ...",
        "quick_prompts" to "وړاندیز شوې پوښتنې",
        "clear_chat" to "چیټ پاک کړئ",
        "copy_response" to "ځواب کاپي کړئ",
        "ai_thinking" to "ای ای د ځواب په فکر کې دی...",
        "main_navigation" to "اصلي لارښود",
        "ai_teacher" to "ای ای استاد سیسټم"
    )
)
